=== ZsoltToth/ilona-tracking/tracking-controller/src/main/resources/graphShema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.uni-miskolc.hu/ilona/graphShema"
	xmlns:tns="http://www.uni-miskolc.hu/ilona/graphShema" elementFormDefault="qualified">

	<simpleType name="graphPointName">
		<restriction base="string">
			<pattern value="[a-zA-Z0-9_]{1,100}"></pattern>
		</restriction>
	</simpleType>

	<simpleType name="graphWeight">
		<restriction base="double">
		</restriction>
	</simpleType>

	<complexType name="node">
		<sequence>
			<element name="name" type="string" minOccurs="1" maxOccurs="1" />
			<element name="description" type="string" default=""/>
		</sequence>
		
	</complexType>

	<complexType name="edge">
		<sequence>
			<element name="from" type="tns:graphPointName" minOccurs="1"
				maxOccurs="1" />
			<element name="to" type="tns:graphPointName" minOccurs="1"
				maxOccurs="1" />
			<element name="weight" type="tns:graphWeight" minOccurs="1"
				maxOccurs="1" default="0" />
			<element name="description" default=""/>
		</sequence>	
	</complexType>

	<complexType name="nodes">
		<sequence>
			<element name="node" type="tns:node" minOccurs="1" maxOccurs="unbounded" />
		</sequence>
	</complexType>

	<complexType name="edges">
		<sequence>
			<element name="edge" type="tns:edge" minOccurs="1" maxOccurs="unbounded" />
		</sequence>
	</complexType>

	<element name="graph">
		<complexType>
			<sequence>
				<element name="nodes" type="tns:nodes" minOccurs="1"
					maxOccurs="1" />
				<element name="edges" type="tns:edges" minOccurs="1"
					maxOccurs="1" />
			</sequence>
		</complexType>
	</element>
</schema>

=== ZsoltToth/ilona-tracking/tracking-controller/src/main/resources/graphFirstFloor.xml
<?xml version="1.1" encoding="UTF-8"?>
<graph:graph xmlns:graph="http://www.uni-miskolc.hu/ilona/graphShema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.uni-miskolc.hu/ilona/graphShema graphShema.xsd ">
	<graph:nodes>
		<graph:node>
			<graph:name>ROOM100_INNER1</graph:name>
			<graph:description>Room 100 inner</graph:description>
		</graph:node>
		<graph:node>
			<graph:name>ROOM100_DOOR</graph:name>
			<graph:description>Room 100 door</graph:description>
		</graph:node>

		<graph:node>
			<graph:name>ROOM101_INNER1</graph:name>
			<graph:description>Room 101 inner</graph:description>
		</graph:node>
		<graph:node>
			<graph:name>ROOM101_DOOR</graph:name>
			<graph:description>Room 100 door</graph:description>
		</graph:node>

		<graph:node>
			<graph:name>ROOM102_INNER1</graph:name>
			<graph:description>Room 102 inner</graph:description>
		</graph:node>
		<graph:node>
			<graph:name>ROOM102_DOOR</graph:name>
			<graph:description>Room 102 door</graph:description>
		</graph:node>

		<graph:node>
			<graph:name>ROOMTOP4_INNER1</graph:name>
			<graph:description>Room top 4 inner</graph:description>
		</graph:node>
		<graph:node>
			<graph:name>ROOMTOP4_DOOR</graph:name>
			<graph:description>Room top 4 door</graph:description>
		</graph:node>

		<graph:node>
			<graph:name>ROOM103_INNER1</graph:name>
			<graph:description>Room 103 inner</graph:description>
		</graph:node>
		<graph:node>
			<graph:name>ROOM103_DOOR</graph:name>
			<graph:description>Room 103 door</graph:description>
		</graph:node>

		<graph:node>
			<graph:name>ROOM104_INNER1</graph:name>
			<graph:description>Room 104 inner</graph:description>
		</graph:node>
		<graph:node>
			<graph:name>ROOM104_DOOR</graph:name>
			<graph:description>Room 104 door</graph:description>
		</graph:node>

		<graph:node>
			<graph:name>TOPCORRIDOR_NODE1</graph:name>
			<graph:description>TOPCORRIDOR_NODE1</graph:description>
		</graph:node>
		<graph:node>
			<graph:name>TOPCORRIDOR_NODE2</graph:name>
			<graph:description>Room 104 door</graph:description>
		</graph:node>
		<graph:node>
			<graph:name>TOPCORRIDOR_NODE3</graph:name>
			<graph:description>Room 104 door</graph:description>
		</graph:node>
		<graph:node>
			<graph:name>TOPCORRIDOR_NODE4</graph:name>
			<graph:description>Room 104 door</graph:description>
		</graph:node>
		<graph:node>
			<graph:name>TOPCORRIDOR_NODE5</graph:name>
			<graph:description>Room 104 door</graph:description>
		</graph:node>
		<graph:node>
			<graph:name>TOPCORRIDOR_NODE6</graph:name>
			<graph:description>Room 104 door</graph:description>
		</graph:node>
		<graph:node>
			<graph:name>TOPCORRIDOR_NODE7</graph:name>
			<graph:description>Room 104 door</graph:description>
		</graph:node>
		<graph:node>
			<graph:name>TOPCORRIDOR_NODE8</graph:name>
			<graph:description>Room 104 door</graph:description>
		</graph:node>

		<graph:node>
			<graph:name>LEFTCORRIDOR_NODE1</graph:name>
			<graph:description>Room 104 door</graph:description>
		</graph:node>
		<graph:node>
			<graph:name>LEFTCORRIDOR_NODE2</graph:name>
			<graph:description>Room 104 door</graph:description>
		</graph:node>
		<graph:node>
			<graph:name>LEFTCORRIDOR_LIFT</graph:name>
			<graph:description>Room 104 door</graph:description>
		</graph:node>
		<graph:node>
			<graph:name>LEFTCORRIDOR_STAIR</graph:name>
			<graph:description>Room 104 door</graph:description>
		</graph:node>
		<graph:node>
			<graph:name>LEFTCORRIDOR_MIDDLE</graph:name>
			<graph:description>Room 104 door</graph:description>
		</graph:node>

		<graph:node>
			<graph:name>MIDDLE_WORKROOM_DOOR</graph:name>
			<graph:description>Room 104 door</graph:description>
		</graph:node>
		<graph:node>
			<graph:name>MIDDLE_WORKROOM_INNER1</graph:name>
			<graph:description>Room 104 door</graph:description>
		</graph:node>

		<graph:node>
			<graph:name>MIDDLE_STORAGEROOM_DOOR</graph:name>
			<graph:description>Room 104 door</graph:description>
		</graph:node>
		<graph:node>
			<graph:name>MIDDLE_STORAGEROOM_INNER1</graph:name>
			<graph:description>Room 104 door</graph:description>
		</graph:node>

		<graph:node>
			<graph:name>MIDDLE_CLEANINGROOM_DOOR</graph:name>
			<graph:description>Room 104 door</graph:description>
		</graph:node>

		<graph:node>
			<graph:name>WOMAN_WC_INNER1</graph:name>
			<graph:description>Room 104 door</graph:description>
		</graph:node>
		<graph:node>
			<graph:name>WOMAN_WC_INNER2</graph:name>
			<graph:description>Room 104 door</graph:description>
		</graph:node>
		<graph:node>
			<graph:name>WOMAN_WC_DOOR</graph:name>
			<graph:description>Room 104 door</graph:description>
		</graph:node>

		<graph:node>
			<graph:name>MIDDLE_DISABLEDROOM_DOOR</graph:name>
			<graph:description>Room 104 door</graph:description>
		</graph:node>

		<graph:node>
			<graph:name>ROOM105_DOOR</graph:name>
			<graph:description>Room 104 door</graph:description>
		</graph:node>
		<graph:node>
			<graph:name>ROOM105_INNER1</graph:name>
			<graph:description>Room 104 door</graph:description>
		</graph:node>

		<graph:node>
			<graph:name>MIDDLEBOTTOM_PRINTERROOM_DOOR</graph:name>
			<graph:description>Room 104 door</graph:description>
		</graph:node>
		<graph:node>
			<graph:name>MIDDLEBOTTOM_PRINTERROOM_INNER1</graph:name>
			<graph:description>Room 104 door</graph:description>
		</graph:node>

		<graph:node>
			<graph:name>MIDDLEBOTTOM_STORAGEROOM_DOOR</graph:name>
			<graph:description>Room 104 door</graph:description>
		</graph:node>
		<graph:node>
			<graph:name>MIDDLEBOTTOM_STORAGEROOM_INNER1</graph:name>
			<graph:description>Room 104 door</graph:description>
		</graph:node>

		<graph:node>
			<graph:name>MIDDLEBOTTOM_DINNERROOM_DOOR</graph:name>
			<graph:description>Room 104 door</graph:description>
		</graph:node>
		<graph:node>
			<graph:name>MIDDLEBOTTOM_DINNERROOM_INNER1</graph:name>
			<graph:description>Room 104 door</graph:description>
		</graph:node>

		<graph:node>
			<graph:name>MIDDLEBOTTOM_WC1_DOOR</graph:name>
			<graph:description>Room 104 door</graph:description>
		</graph:node>
		<graph:node>
			<graph:name>MIDDLEBOTTOM_WC2_DOOR</graph:name>
			<graph:description>Room 104 door</graph:description>
		</graph:node>

		<graph:node>
			<graph:name>MIDDLEBOTTOM_MANWC_DOOR</graph:name>
			<graph:description>Room 104 door</graph:description>
		</graph:node>
		<graph:node>
			<graph:name>MIDDLEBOTTOM_MANWC_INNER1</graph:name>
			<graph:description>Room 104 door</graph:description>
		</graph:node>
		<graph:node>
			<graph:name>MIDDLEBOTTOM_MANWC_INNER2</graph:name>
			<graph:description>Room 104 door</graph:description>
		</graph:node>

		<graph:node>
			<graph:name>ROOM106_DOOR</graph:name>
			<graph:description>Room 104 door</graph:description>
		</graph:node>
		<graph:node>
			<graph:name>ROOM106_INNER1</graph:name>
			<graph:description>Room 104 door</graph:description>
		</graph:node>

		<graph:node>
			<graph:name>RIGHTCORRIDOR_NODE1</graph:name>
			<graph:description>Room 104 door</graph:description>
		</graph:node>
		<graph:node>
			<graph:name>RIGHTCORRIDOR_NODE2</graph:name>
			<graph:description>Room 104 door</graph:description>
		</graph:node>
		<graph:node>
			<graph:name>RIGHTCORRIDOR_NODE3</graph:name>
			<graph:description>Room 104 door</graph:description>
		</graph:node>

		<graph:node>
			<graph:name>LIBRARY_DOOR</graph:name>
			<graph:description>Room 104 door</graph:description>
		</graph:node>
		<graph:node>
			<graph:name>LIBRARY_INNER1</graph:name>
			<graph:description>Room 104 door</graph:description>
		</graph:node>

		<graph:node>
			<graph:name>RECEPION_DOOR</graph:name>
			<graph:description>Room 104 door</graph:description>
		</graph:node>
		<graph:node>
			<graph:name>RECEPION_INNER1</graph:name>
			<graph:description>Room 104 door</graph:description>
		</graph:node>
		<graph:node>
			<graph:name>RECEPION_INNER2</graph:name>
			<graph:description>Room 104 door</graph:description>
		</graph:node>

		<graph:node>
			<graph:name>DEPARTMENTCENTER_DOOR</graph:name>
			<graph:description>Room 104 door</graph:description>
		</graph:node>
		<graph:node>
			<graph:name>DEPARTMENTCENTER_INNER1</graph:name>
			<graph:description>Room 104 door</graph:description>
		</graph:node>
		<graph:node>
			<graph:name>DEPARTMENTCENTER_INNER2</graph:name>
			<graph:description>Room 104 door</graph:description>
		</graph:node>

		<graph:node>
			<graph:name>TEACHERROOM1_DOOR</graph:name>
			<graph:description>Room 104 door</graph:description>
		</graph:node>
		<graph:node>
			<graph:name>TEACHERROOM1_INNER1</graph:name>
			<graph:description>Room 104 door</graph:description>
		</graph:node>
		<graph:node>
			<graph:name>TEACHERROOM1_INNER2</graph:name>
			<graph:description>Room 104 door</graph:description>
		</graph:node>

		<graph:node>
			<graph:name>TEACHERROOM2_DOOR</graph:name>
			<graph:description>Room 104 door</graph:description>
		</graph:node>
		<graph:node>
			<graph:name>TEACHERROOM2_INNER1</graph:name>
			<graph:description>Room 104 door</graph:description>
		</graph:node>
		<graph:node>
			<graph:name>TEACHERROOM2_INNER2</graph:name>
			<graph:description>Room 104 door</graph:description>
		</graph:node>

		<graph:node>
			<graph:name>TEACHERROOM3_DOOR</graph:name>
			<graph:description>Room 104 door</graph:description>
		</graph:node>
		<graph:node>
			<graph:name>TEACHERROOM3_INNER1</graph:name>
			<graph:description>Room 104 door</graph:description>
		</graph:node>
		<graph:node>
			<graph:name>TEACHERROOM3_INNER2</graph:name>
			<graph:description>Room 104 door</graph:description>
		</graph:node>

		<graph:node>
			<graph:name>TEACHERROOM4_DOOR</graph:name>
